# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pylint

on:
  push:
    branches: [ pylint ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Pylint
      run: |
        pip install pylint
        pylint app/*.py -r y > /tmp/pylint-report.txt
        if [ $(cat /tmp/pylint-report.txt 2> /dev/null | tail -n2 | awk '{print $7}' | cut -d"/" -f1) -leq 5 ]; set -e o pipefail;